name: Tests (7.3)
on:
  repository_dispatch:
    types:
      - trigger-73-tests

jobs:
  code_style:
    name: Test code style
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: php-7.3
      - name: Install Dependencies
        run: composer install
      - name: Test code style
        run: composer fixer -- --dry-run
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: php-7.3
      - name: Install Dependencies
        run: composer install
      - name: Run static analysis
        run: composer phpstan
